version: '3.2'
# *********************************************************************
# *                               ELK-Stack                           *
# *********************************************************************
#
# ELK-Stack involve the installation of the following services:
# 1. Logstash (Version 7.9.2).
# 2. Elasticsearch with xpack-security plugin (Version 7.9.2).
# 3. Kibana (Version 7.9.2).
services:
# ELASTICSEARCH
# -------------

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
    container_name: elasticsearch
    volumes:
      - type: bind
        source: ./elasticsearch/config/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: volume
        source: elasticsearch
        target: /usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: elkstack2020
      discovery.type: single-node
    networks:
      - elkstack
# Notes:
# a) Single-node - Used to bind transport to an external interface for testing their usage of the transport client.
# b) Port 9200 - Search, Aggregations and Monitoring.
# c) Port 9300 - Communication between nodes.
# ----------------------------------------------------------------------

# LOGSTASH
# --------

  logstash:
    image: docker.elastic.co/logstash/logstash:7.9.2         
    container_name: logstash
    volumes:
      - type: bind
        source: ./logstash/config/logstash.yml
        target: /usr/share/logstash/config/logstash.yml
        read_only: true
      - type: bind
        source: ./logstash/pipeline
        target: /usr/share/logstash/pipeline
        read_only: true
    ports:
      - "5044:5044"
      - "5000:5000/tcp"
      - "5000:5000/udp"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx512m -Xms512m"
    networks:
      - elkstack
    depends_on:
      - elasticsearch
# Notes:
# a) LS_JAVA_OPTS - Heap size for Java Virtual Machine
# b) Port 5044 - Default Beats port.
# c) Port 5000 - Default Logstash port. 
# d) Port 9600 - Web API calls.
# ----------------------------------------------------------------------

# KIBANA

  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.2
    container_name: kibana
    volumes:
      - type: bind
        source: ./kibana/config/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true
    ports:
      - "5601:5601"
    networks:
      - elkstack
    depends_on:
      - elasticsearch
# Notes:
# a) Port 5601 - Kibana Web Application default port.
# ----------------------------------------------------------------------

# PARAMETERS
# ----------

# Networklogstash 5000 port
# ------
networks:
  elkstack:
    driver: bridge

# Volumes
# -------
volumes:
  elasticsearch:
