---
## Logstash configuration
#
http.host: "0.0.0.0"
xpack.monitoring.elasticsearch.hosts: [ "http://elasticsearch:9200" ]

## X-Pack security credentials
#
xpack.monitoring.enabled: true
# At the end of the trial period, some features operate in a degraded mode. You can revert to Basic, extend the trial, or purchase a subscription.
xpack.monitoring.elasticsearch.username: elastic
xpack.monitoring.elasticsearch.password: elkstack2020
